apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ostad-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "tutul-k8s-1.rfft.nl"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ostad-app-1
                port:
                  number: 80
    - host: "tutul-k8s-2.rfft.nl"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ostad-app-2
                port:
                  number: 80
