apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostad-app-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ostad-app-2
  template:
    metadata:
      labels:
        app: ostad-app-2
    spec:
      containers:
      - name: ostad-app-2-container
        image: tutulchakma/chat-app:latest
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: ostad-app-2-service
spec:
  type: NodePort
  selector:
    app: ostad-app-2
  ports:
  - port: 80
    targetPort: 3000
  
